import { randomUUID } from 'node:crypto';
import { emptyCvDocument, type CvDocument } from '@cv/shared';
import {
  LlmError,
  type GenerateCvRequest,
  type LlmClient,
  type LlmResponse,
} from './llm-client.js';

type Step =
  | { kind: 'valid'; document?: CvDocument }
  | { kind: 'invalid' }
  | { kind: 'transient'; status: number }
  | { kind: 'permanent'; status: number }
  | { kind: 'slow'; ms: number };

function sleep(ms: number, signal: AbortSignal): Promise<void> {
  if (ms <= 0) return Promise.resolve();
  return new Promise((resolve, reject) => {
    if (signal.aborted) return reject(new LlmError('Request timed out', true));
    const timer = setTimeout(() => {
      signal.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    const onAbort = () => {
      clearTimeout(timer);
      reject(new LlmError('Request timed out', true));
    };
    signal.addEventListener('abort', onAbort, { once: true });
  });
}

/**
 * A deterministic draft built from the source lines, so the pipeline (and the browser demo)
 * works end to end without a key. Not grounded, not role-targeted: that is Phase 3.
 */
export function fakeCvFromSources(request: Pick<GenerateCvRequest, 'sources'>): CvDocument {
  const lines = request.sources
    .flatMap((source) => source.text.split(/\r?\n/))
    .map((line) => line.replace(/\s+/g, ' ').trim())
    .filter((line) => line.length >= 3);
  const document = emptyCvDocument();
  document.summary = 'Draft generated by the offline fake AI from your source text.';
  document.experience = [
    {
      id: randomUUID(),
      company: 'From your source',
      title: '',
      dates: null,
      bullets: lines.slice(0, 6).map((line) => ({ id: randomUUID(), text: line.slice(0, 300) })),
    },
  ];
  return document;
}

/**
 * Scripted `LlmClient` for tests, the e2e stack, and Phase 2 (testing.md, "FakeLlmClient
 * scenarios"). Each call consumes the next scripted step; with an empty script every call
 * returns a valid draft built from the source. `delayMs` applies to every call.
 */
export class FakeLlmClient implements LlmClient {
  readonly calls: GenerateCvRequest[] = [];
  private readonly script: Step[] = [];

  constructor(private readonly options: { delayMs?: number } = {}) {}

  /** A valid structured response (the given document, or one built from the source). */
  valid(document?: CvDocument): this {
    this.script.push({ kind: 'valid', document });
    return this;
  }

  /** `n` responses that fail the schema, then whatever comes next (AC-6.6 re-requests). */
  invalid(n = 1): this {
    for (let i = 0; i < n; i++) this.script.push({ kind: 'invalid' });
    return this;
  }

  /** A response containing facts the source does not support; grounding removes them (Phase 3). */
  fabricated(document: CvDocument): this {
    return this.valid(document);
  }

  /** `429` / `5xx` / `529` / timeout: BullMQ retries (AC-5.5). */
  transient(status = 529): this {
    this.script.push({ kind: 'transient', status });
    return this;
  }

  /** `400` / `401`: the job fails at once (AC-5.6). */
  permanent(status = 400): this {
    this.script.push({ kind: 'permanent', status });
    return this;
  }

  /** A call that takes `ms` before answering with the next step (deadline, shutdown tests). */
  slow(ms: number): this {
    this.script.push({ kind: 'slow', ms });
    return this;
  }

  async generateCv(request: GenerateCvRequest): Promise<LlmResponse> {
    this.calls.push(request);
    await sleep(this.options.delayMs ?? 0, request.signal);

    let step = this.script.shift() ?? { kind: 'valid' };
    while (step.kind === 'slow') {
      await sleep(step.ms, request.signal);
      step = this.script.shift() ?? { kind: 'valid' };
    }

    switch (step.kind) {
      case 'valid':
        return { output: step.document ?? fakeCvFromSources(request) };
      case 'invalid':
        return { output: { summary: 42, experience: 'not a list' } };
      case 'transient':
        throw new LlmError(`Fake transient error ${step.status}`, true, step.status);
      case 'permanent':
        throw new LlmError(`Fake permanent error ${step.status}`, false, step.status);
    }
  }
}
